AWSTemplateFormatVersion: '2010-09-09'
Transform: "AWS::Serverless-2016-10-31"
Description: >
    line-bot star-rain deploy process
    
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 30  # in seconds
Parameters: 
  ENVR:
    Type: String
    Description: The envr prefix we use to create AWS resources.

Resources:
    #######################################################
    ##### Start of API Gateway and associated lambdas #####
    #######################################################
    ServerlessApi:
      Type: AWS::Serverless::Api
      Properties:
        StageName: !Sub ${ENVR}
        EndpointConfiguration: REGIONAL
        DefinitionBody: {
            "swagger": "2.0",
            "info": {
              "version": "2020-01-06T07:45:41Z",
              "title": !Sub "${ENVR}-star-rain-api"
            },
            "paths": {
              "/star-rain": {
                "post": {
                  "produces": [
                    "application/json"
                  ],
                  "responses": {
                    "200": {
                      "description": "200 response",
                      "schema": {
                        "$ref": "#/definitions/Empty"
                      }
                    }
                  },
                  "x-amazon-apigateway-integration": {
                    "uri": !Sub "arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-1:278497686406:function:${ENVR}-star-rain/invocations",
                    "responses": {
                      "default": {
                        "statusCode": "200"
                      }
                    },
                    "passthroughBehavior": "when_no_match",
                    "httpMethod": "POST",
                    "contentHandling": "CONVERT_TO_TEXT",
                    "type": "aws"
                  }
                }
              },
            },
            "definitions": {
              "Empty": {
                "type": "object",
                "title": "Empty Schema"
              }
            }
          }
    LambdaStarRain:
      Type: AWS::Serverless::Function
      Properties:
        Handler: index.starRain
        Runtime: nodejs14.x
        FunctionName: !Sub ${ENVR}-star-rain
        Role: arn:aws:iam::278497686406:role/line-bot
        CodeUri: ../../dist/webpack/lambda
        MemorySize: 128
    InvokePermissionStarRain:
      Type: AWS::Lambda::Permission
      DependsOn: [ServerlessApi, LambdaStarRain]
      Properties:
          FunctionName: !Sub ${ENVR}-star-rain
          Action: 'lambda:InvokeFunction'
          Principal: apigateway.amazonaws.com
          SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ServerlessApi}/*